---
language: ruby
script: bundle exec middleman build
env:
  global:
    - GIT_COMMITTER_NAME='ngs@travis-ci'
    - GIT_COMMITTER_EMAIL='a+travis@ngs.io'
    - GIT_AUTHOR_NAME='ngs@travis-ci'
    - GIT_AUTHOR_EMAIL='a+travis@ngs.io'
    - secure: "NCmovQmReTeBMYetXtyRhDNoqi7koNmGGy4V6xwm/Bk7xPYLLK9a8GQawABgMJVIATn3KGKGKQUsWLNDT5rXB8YBwPw/xM+OcErFLzDAKClWLjiscMqwX8sCd9qRK8R3ERHoQ4LtP120V7x7M0eHTlqM+e0ejuEgAvuVJyesgvE="
after_success:
  - '[ "$TRAVIS_BRANCH" == "master" ] && [ $GH_TOKEN ] && bundle exec middleman deploy >/dev/null 2>&1'

