---
language: ruby
rvm:
  - 2.0.0
cache: bundler
script: bundle exec middleman build
branches:
  only:
    - source
env:
  global:
    - GIT_COMMITTER_NAME='ngs@travis-ci'
    - GIT_COMMITTER_EMAIL='a+travis@ngs.io'
    - GIT_AUTHOR_NAME='ngs@travis-ci'
    - GIT_AUTHOR_EMAIL='a+travis@ngs.io'
after_success:
  - '[ $GH_TOKEN ] && bundle exec middleman deploy >/dev/null 2>&1'
notifications:
  on_success: always
  on_failure: always
  on_start: always
  webhooks:
    - 'http://ngs-hubot.herokuapp.com/travisci/hooks'

